.github/ISSUE_TEMPLATE/bug.yml, .github/ISSUE_TEMPLATE/feature.yml, .github/ISSUE_TEMPLATE/help.yml, .github/workflows/auto-project.yml
- bug, feature, help 이슈 템플릿 추가했습니다.
- GitHub 이슈를 프로젝트에 자동으로 할당하기 위한 워크플로우 구성했습니다.
- bug, feature, help 이슈 템플릿 추가
- help 이모지 변경
- GitHub 이슈를 프로젝트에 자동으로 할당하기 위한 워크플로우 구성
=> [settings] 깃허브 이슈 템플릿 추가,  프로젝트에 자동 할당 워크플로우 구성

.eslintrc.cjs, package-lock.json, package.json
- eslint 설치 및 설정 
- airbnb 스타일가이드로 설치 
- eslint 설정 파일의 확장자를 .cjs로 변경하여 ES모듈을 인식
- package.json 업데이트
- ## 📄 기타 
- 작업 내용: https://github.com/Dev-FE-1/idle-intranet-service/issues/8 참조
=> [settings]eslint 설치 및 설정 

.eslintrc.cjs, .stylelintrc.cjs, package-lock.json, package.json, server/database.js, server/index.js, src/counter.js, src/main.js, src/style.css, vite.config.js
- 스타일린트 설치 및 코드 스타일 정리
- 스타일린트 설치
- 코드 스타일 정리
- ## 📄 기타 
- 작업 내용: https://github.com/Dev-FE-1/idle-intranet-service/issues/14 참조
=> [settings] 스타일린트 설치 및 코드 스타일 정리

index.html, src/components/Layout.js, src/components/NavBar/NavBar.css, src/index.css, src/routes/Route.js
자잘한 오류 및 디자인 수정
- activeNavBar 호출 시 불필요한 인자 제거
- Layout.js의 this.Header, this.NavBar 초기화 제거
- 웹폰트 최적화
- 네비게이션 디자인 수정
- 불필요한 코드 삭제
- 웹 폰트 `@import`에서 link로 수정
- 네비게이션 프로필 위 여백 제거 및 active 상태 색상 변경
Thanks to @HSjjs98 👍
=> [Refactor] 자잘한 오류 및 디자인 수정

src/components/Button/Button.css, src/index.css
Button 컴포넌트 hover 스타일 수정
hover 배경색 수정했습니다!
- index.css에 hover 변수 추가 (나중에 다른 곳에서도 필요할까봐)
=> [Design] Button 컴포넌트 hover 스타일 수정

src/components/Input/Input.css, src/components/Pagination/Pagination.css, src/components/Pagination/Pagination.js, src/pages/Members/Members.css, src/pages/Members/Members.js
구성원 페이지 디자인 수정 했습니다!
구성원 페이지 및 해당 페이지에서 사용한 컴포넌트의 사이즈 조절 등 디자인 수정 작업
- 페이지네이션 사이즈 수정
- 기타 폰트 사이즈 수정
- 테이블 CSS 오류 수정
- Input 사이즈 수정
=> [Design] 구성원 페이지 디자인 수정

src/components/NavBar/Menu.js, src/pages/Members/Members.js, src/pages/Profile/Profile.js, src/pages/WorkManage/WorkManage.js, src/routes/Route.js, src/utils/constants.js, src/utils/matchRoute.js
동적 라우팅 기능을 추가했습니다.
- 동적 라우팅 기능 추가
- 라우터 구조 변경
- 기존 switch문을 routes 객체를 만들어 대체함
- 하위 페이지에 들어가도 메뉴가 active 상태가 될 수 있도록 구현
- 로그인하지 않은 사용자는 로그인 페이지 외 다른 페이지를 볼 수 없도록 구현
- constants.js에서 변수명 `MENUS`를 `PATH_TITLE`로 변경
로그인 체크는 임시로 넣어뒀습니다!
=> [Feat] 동적 라우팅 기능 추가

.eslintrc.cjs, src/App.js, src/components/Button/Button.js, src/components/Icon/Icon.js, src/components/Input/Input.js, src/components/Modal/Modal.css, src/components/Modal/Modal.js, src/components/NavBar/Menu.js, src/components/NavBar/NavBar.css, src/components/Pagination/Pagination.js, src/components/PersonalInfo/PersonalDetails.css, src/components/PersonalInfo/PersonalDetails.js, src/components/PersonalInfo/PersonalInfo.js, src/components/PersonalInfo/ProfileInfo.js, src/components/PersonalInfo/WorkInfo.js, src/components/SignInForm/SignInForm.js, src/pages/404/PageNotFound.js, src/pages/Home/Home.js, src/pages/Members/Members.js, src/pages/Profile/Profile.js, src/pages/WorkManage/WorkManage.js, src/pages/index.js, src/routes/Route.js, src/utils/icons.js, src/utils/matchRoute.js
ESLint 스타일링 관련 코드 정리 및 기능 개선 작업
이번 업데이트는 주로 코드의 스타일과 기능 개선에 초점을 맞췄습니다. 특히, ESLint와 Stylelint 오류를 해결하여 코드의 일관성과 품질을 향상시켰습니다.
• 스타일 속성 이름 변경: type을 HTML 표준 속성으로 유지하고 스타일 지정 속성을 variant로 변경하여 속성명 충돌을 해결했습니다.
• 리팩토링: matchRoute 함수에서 for..in 대신 Object.keys().forEach()를 사용하여 안전하게 속성을 순회하도록 개선했습니다. 이 변경은 ESLint 오류 덕분에 알게 되었습니다.
• 기능 개선: popstate 이벤트 처리 로직을 수정하여 브라우저의 뒤로 가기 버튼 사용 시 적절한 페이지를 렌더링하도록 했습니다.
• ESLint 및 Stylelint 오류 해결: 코드 전반에 걸친 다양한 Lint 오류를 해결하여, 보다 안정적이고 일관된 코드 베이스를 유지할 수 있게 되었습니다.
=> [Fix/Refactor]ESLint, 스타일링 관련 코드 정리 및 기능 개선 작업

.gitignore, package-lock.json, package.json, server/index.js, src/fetchData.js
API GET 요청 엔드 포인트를 추가했습니다.
- API GET 요청 엔드포인트 추가
- 페이지네이션을 이용하는 구성원, 근태 기록, 휴가 기록은 우선 테스트 코드 상 10개씩 출력되도록 만들어뒀습니다   
- 테스트 코드 수정
- .env 파일 추가 (.gitignore로 관리하고 있으니 직접 추가해주셔야 합니다!)
- 파일 만드셔서 `VITE_SERVER_URL=http://localhost:8080` 라고 입력하면 fetchData.js에 있는 테스트 코드로 확인해보실 수 있습니다
- cors 추가 (npm install 필요)
`fetchData.js`에 있는 코드는 테스트용이라 try catch 등 예외 처리는 크게 해두지 않은 상태입니다!
=> [Feat] API GET 요청 기능 추가

package-lock.json, package.json, src/components/PersonalInfo/PersonalInfo.js, src/pages/Profile/Profile.js, src/routes/Route.js
프로필 페이지에서 현재 시각을 보여주는 기능을 추가했습니다.
- 새로고침 하지 않아도 1분마다 시간 업데이트
- 다른 페이지로 이동하면 clearTimeout
- dayjs 라이브러리 추가
바뀌는 거 한 번 놓치면 1분 기다리셔야 함..
=> [Feat] 프로필 페이지에 현재 시각 표시

package-lock.json, src/pages/Home/Home.css, src/pages/Home/Home.js, src/pages/Profile/Profile.js
홈페이지 스타일링 및 약간의 html 구조 변경
- 홈페이지 스타일 수정
- 다른 페이지와 클래스가 겹쳐서 생긴 문제 해결 
- 태그 대신 클래스 속성을 이용해 스타일링
-`server/index.js`에서 `authenticateToken`을 사용하고 있어 공지사항 갤러리 이미지가 불러와지지 않는 이슈가 있습니다.
- 현재 공지사항을 불러오는 코드에는 인증 확인하는 부분이 없어서
- `app.get('/api/announcements', authenticateToken, (req, res) => {` 에서 `authenticateToken` 을 지우고 확인해보시면 됩니다!
=> [Design] 홈페이지 스타일링 수정

.env, src/components/Select/Select.css, src/components/Select/Select.js
**Select 컴포넌트 추가**
- Select 클래스 구현
- `contents`: 항목 리스트
- `onSelect`: 선택 콜백 함수
- `excludeFirst`: 사용자가 항목을 선택할 때 호출되는 함수
- `roundedBorder`, `small`: 스타일 옵션
- 드롭다운 열기/닫기 기능 추가
- 선택 항목 업데이트 및 HTML 렌더링
- CSS 스타일 추가
- 이벤트 리스너 추가
- 요청사항으로 env파일도 함께 지움.
- 피그마에서 underlined Select 컴포넌트를 디자인할 때는 화살표 없이 작업했지만, 퍼블리싱을 진행하면서 화살표를 추가하는 것이 더 나아 보였습니다. 전체적으로 조합해봤을 때 어울리지 않으면 화살표를 제거할 수도 있습니다.
- id값을 넣은 이유는 컴포넌트를 식별하기 위해서 추가했습니다.
- 아래 코드를 복사해서 WorkManage.js에서 테스트용으로 사용해 보세요.
```
import Main from '../../components/Main.js';
import Select from '../../components/Select/Select.js';
import Title from '../../components/Title/Title.js';
import { PATH_TITLE } from '../../utils/constants.js';
import './WorkManage.css';
const vacation = [
'전체 휴가',
'연차',
'반차',
'출산 휴가',
'배우자 출산 휴가',
'여성 휴가',
'가족 돌봄 휴가',
'기타휴가',
]; …
```
=> [Feat] Select 컴포넌트 추가 및 env 파일 삭제

.gitignore, 404.html, index.html, package-lock.json, package.json, src/components/API/AuthService.js, src/components/API/MemberService.js, src/fetchData.js, src/pages/404/PageNotFound.js, src/utils/constants.js, vite.config.js
github pages 배포
github pages로 배포 작업
- apiBaseUrl 추가
- gh-pages 패키지 추가
배포.....쉽지 않네요......
.env에 파일에 추가
VITE_BASE_URL=/idle-intranet-service
VITE_SERVER_URL=http://localhost:8080
=> [Deploy] github pages 배포

src/App.js, src/components/Header/Header.js, src/components/Layout.js, src/components/Store.js, src/pages/404/PageNotFound.css, src/pages/404/PageNotFound.js, src/routes/Route.js
404, ESLint, console 에러를 해결했습니다!
- 로그인하기 전 user 정보 요청을 보내서 console창에 에러 메시지가 뜨는 오류 해결
- 404 페이지에서 홈으로 이동 버튼 처리가 제대로 작동하지 않는 오류 해결
- ESLint 에러 해결
버그 삼총사... 에러는 이제 그만..
=> [Bug] 404, ESLint, console 에러 해결

src/components/Header/Header.js, src/components/PersonalInfo/PersonalDetails.js, src/components/PersonalInfo/PersonalInfo.js, src/components/PersonalInfo/ProfileInfo.js, src/components/Store.js, src/pages/Home/Home.js, src/pages/Profile/Profile.js
ProfileInfo와 PersonalDetails 컴포넌트 재사용성 향상
구성원 상세페이지에서도 활용할 수 있도록 수정했습니다.
- 컴포넌트 구조 변경
수정된 화면 또는 기능을 시연할 수 있는 스크린샷을 첨부할 수 있습니다.
추가적으로 전달하고 싶은 내용이나 특별한 요구 사항이 있으면 작성해 주세요.
=> [Refactor] ProfileInfo와 PersonalDetails 컴포넌트 재사용성 향상

package-lock.json, package.json, server/cloudinary.js, server/index.js, src/api/config.js, src/api/endpoints/user.js, src/components/Avatar/Avatar.css, src/components/Button/IconButton.css, src/components/Button/IconButton.js, src/components/Input/Input.js, src/components/Modal/Modal.css, src/components/Modal/Modal.js, src/components/PersonalInfo/EditProfileButton.js, src/components/PersonalInfo/EditProfileForm.css, src/components/PersonalInfo/EditProfileForm.js, src/components/PersonalInfo/ProfileInfo.css, src/components/PersonalInfo/ProfileInfo.js, src/pages/Home/Home.css, src/utils/icons.js, src/utils/profileImage.js
프로필 정보(프로필 이미지, 전화번호, 주소) 수정 기능을 구현했습니다.
- 프로필 이미지 수정
- 사용자가 이미지 파일을 추가할 수 있음
- 이미지 추가 대신 랜덤 프로필 생성 기능을 이용할 수 있음
- IconButton 컴포넌트 추가
- Modal 컴포넌트에 기능 추가
- cloudinary 추가 (`npm install` 필요)
- api endpoint 추가 (서버 재시작 필요)
=> [Feat] 프로필 정보 수정 기능

src/api/endpoints/announcement.js, src/components/Announcements/GalleryItem.js, src/components/Table/Table.css, src/pages/Announcement/Announcement.js, src/pages/Members/Members.css, src/pages/Members/Members.js, src/routes/Route.js, src/utils/constants.js
공지사항 갤러리 상세 페이지 템플릿 추가 및 순환 참조 오류를 해결했습니다.
- 난아님이 작업하실 공지사항 갤러리 상세 페이지 라우팅 및 초기 세팅
- Members 페이지 순환 참조 오류 해결
- Members 페이지에서 Route 인스턴스를 생성하고 있어 순환 참조가 발생했습니다.
- pushState 대신 링크 태그로 감싸서 라우팅이 정상적으로 동작하도록 수정했습니다.
- 이거 변경하다가 오타도 발견해서 수정 ㅎㅎ
수정된 화면 또는 기능을 시연할 수 있는 스크린샷을 첨부할 수 있습니다.
추가적으로 전달하고 싶은 내용이나 특별한 요구 사항이 있으면 작성해 주세요.
=> [Feat/Bug] 공지사항 갤러리 상세 페이지 템플릿 추가 및 순환 참조 오류 해결

src/pages/Announcement/Announcement.css, src/pages/Announcement/Announcement.js
공지사항 페이지 수정하고 CSS 작업했습니다.
- 버튼 태그 이름 수정 back-button-container
- 사용하지 않는 태그 확인
- 확인용 console.log 제거
- 미디어쿼리 글자 가로넓이 조절
- back-button 태그 이름이 back-button-container로 변경되었습니다.
- 사용하지 않는 태그 제거 했습니다
- 확인용 console.log 제거 했습니다
- 미디어쿼리 글자 가로넓이 조절 했습니다
버튼 아이콘 크기조절 부탁드립니다!
=> [feat] 공지사항 수정 작업 (#133)

src/pages/Announcement/Announcement.css, src/pages/Announcement/Announcement.js
공지사항 상세 페이지 디자인 수정
버튼 사이즈 등 자잘한 디자인 수정했습니다!
=> [Design] 공지사항 상세 페이지 디자인 수정

src/pages/WorkManage/WorkManage.js, src/utils/vacation.js
**첫진입시 근무화면 페이지 진입, 기타 휴가 띄어쓰기**
첫진입시 근무화면 페이지 진입, 기타 휴가 띄어쓰기
첫진입시 근무화면 페이지 진입, 기타 휴가 띄어쓰기
=> [Feat, Chore] 첫진입시 근무화면 페이지 진입, 기타 휴가 띄어쓰기

src/components/Select/Select.css, src/components/WorkManagement/VacationTab/VacationCard.css, src/components/WorkManagement/VacationTab/VacationCards.css, src/components/WorkManagement/VacationTab/VacationHistories.css, src/pages/WorkManage/WorkManage.css
근무/휴가 페이지 자잘한 디자인 수정 했습니다!
- 폰트 사이즈 조절 등 자잘한 수정...
추가적으로 전달하고 싶은 내용이나 특별한 요구 사항이 있으면 작성해 주세요.
=> [Design] 근무/휴가 페이지 UI 스타일 수정

server/index.js
CORS 오류가 생겨서 origin을 추가했습니다
- cors origin 추가
- 개발 환경에서도 작동할 수 있도록 localhost도 추가함 
비상..
추가적으로 전달하고 싶은 내용이나 특별한 요구 사항이 있으면 작성해 주세요.
=> [Fix] cors origin 추가
